### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by Coolhacker1332** [topji/DiscSpam#33]
[x] Suspicious words found!:
[!]   token
[!]   discord
[!]   steal
[x] Urls found!:
[!]   https://discord.comif-unmodified-sinceillegal
[!]   https://discord.com/channels/%sin
[!]   https://discord.com/channels/%s/%sillegal
[!]   https://discord.com/api/v9/invites/%sinternal
[!]   https://discord.com/api/v9/users/@me/guilds/%sinvalid
[!]   https://discord.com/api/v9/guilds/%s/members/%sinvalid
[!]   https://discordapp.com/api/v9/channels/%s/messagesinvalid
[!]   https://discord.com/api/v9/channels/%s/messages/%s/reactions/%s/%stls

**Comment by topji** [comment]
What even is this?

**Comment by Coolhacker1332** [comment]
WANT HELP WITH TOKEN LOGGING DM ME [AFK] New Micah Langley#0001

**Comment by Coolhacker1332** [comment]
scam

**Comment by topji** [comment]
Not quite sure what is going on here, some kind of weird behavior but none of the less I am closing this issue.
